apiVersion: v1
kind: Service
metadata:
  name: project-name
  namespace: &namespace&
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: http1
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http2
  selector:
    app: project-name
  type: NodePort
